name: Task Manager CI

on:
  push:
    branches:
      - main
    paths:
      - task-manager/**
  pull_request:
    branches:
      - main
    paths:
      - task-manager/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.5

      - name: Run tests
        run: |
          cd task-manager/test
          go test -tags='!secret' ./...

